### ISSUE TITLE
Plugin won't install via Pip

### ISSUE THREAD

**Issue by Kentoseth** [SangSatori/pelican-next-meetup#2]
This plugin won't install via Pip, as it looks like the pip version is outdated (or something else).

Also, it looks like the plugin works for the latest 2.7 release, so you should add support for that.

 - [x] Fix Pypi version of plugin
 - [x] Add info for 2.7 support
 - [x] Change github link on Pypi page (currently goes to 404)

**Comment by SangSatori** [comment]
Thanks for pointing this out - will get to this ASAP on all 3 points, most likely in a day to two (upcoming trip abroad). Will keep you posted!

**Comment by SangSatori** [comment]
I switched to automatic deployment to [PyPI](https://pypi.python.org/pypi/pelican-next-meetup) using [TravisCI](http://travis-ci.org/) & saw current `v0.2.2` successfully install under Python 2.7. Also updated the repo link to correct one. Let me know if things work/not work for you.
