### ISSUE TITLE
Scenario where there is no meetup next but the code still runs

### ISSUE THREAD

**Issue by Kentoseth** [SangSatori/pelican-next-meetup#3]
In situations where you want the plugin to still work when no new meetup is next (meaning that the blog must still compile and generate HTML), we should probably have a situation/check where if no "next meetup" is found, some text is returned instead. eg.

`no meetup announced yet`

I am opening this issue because I thought about this test when attempting to schedule a CRON (to auto-build the site) and I realized that a new meetup may not always be announced.

I also tested it and I got an error when testing a meetup group that doesn't have a meetup announced:
```
WARNING: Feeds generated without SITEURL set properly may not be valid
ERROR: Could not process pages/home.md
  | IndexError: list index out of range
ERROR: Could not process pages/talks.md
  | IndexError: list index out of range
ERROR: Could not process pages/about.md
  | IndexError: list index out of range
CRITICAL: UndefinedError: 'next_meetup' is undefined
```

**Comment by SangSatori** [comment]
Thanks, @Kentoseth! Plugin was originally made for a very specific and simple use-case, and I agree that there's room for improvement. I'll keep you posted.

**Comment by Kentoseth** [comment]
I have found a work-around within the template files (eg. index.html) that makes the articles compile, but pages will not compile due to the error.

The work-around is:
```
{% if next_meetup %}
    <p> do something </p>
{% else %}
    <p>No meetup announced yet</p>
{% endif%}
```

But as I mentioned above, I will still get errors for pages, like this one:

> Starting new HTTPS connection (1): api.meetup.com
> DEBUG: Setting read timeout to None
> DEBUG: "GET /2/events?group_urlname=some-test-meetup&photo-host=public&page=1&sign=True HTTP/1.1" 200 436
> ERROR: Could not process pages/home.md
>   | IndexError: list index out of range

So I think we just need an `else` clause to address the `out of range` errors.

**Comment by SangSatori** [comment]
`next_meetup` should now be falsy if no next meetup has been scheduled as of latest, without `out of range` occurring.
